////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
# Hop Expression Plugin
:url-sonarcloud: https://sonarcloud.io/dashboard?id=hop-expression

image:https://sonarcloud.io/api/project_badges/measure?project=hop-expression&metric=alert_status[Sonarcloud,link={url-sonarcloud}]

## Overview

This plugin provides 4 transformations that use the power of an expression language.

* The `Expression` transformation calculate fields with expression 
image:https://raw.githubusercontent.com/nadment/hop-expression/master/plugins/src/main/resources/expression.svg[Expression]

* The `Route` transformation switches rows according to an expression condition
image:https://raw.githubusercontent.com/nadment/hop-expression/master/plugins/src/main/resources/route.svg[Route]

* The `Where` transformation filter rows with expression condition
image:https://raw.githubusercontent.com/nadment/hop-expression/master/plugins/src/main/resources/where.svg[Where]

* The `Aggregate` transformation uses aggregation functions to calculate values on groups of rows.
image:https://raw.githubusercontent.com/nadment/hop-expression/master/plugins/src/main/resources/aggregate.svg[Where]

## Expression language

An expression is a combination of one or more literal values, resolvable identifiers, operators and functions that evaluate to a value.

----
/** 
 * Multi line comment
 */

case 
  when REGION_ID<0 then Upper(Left(LABEL,5))
  when REGION_ID between 0 and 100 then InitCap(Substr("LABEL FR",8,50)) 
  else To_Char([YEAR]+1,'FM9999') || ' XXX '
end
----
* Supports 7 data types: `Boolean` `Integer` `Number` `String` `Date` `Binary` `Json` 
* Constant value: `TRUE`, `FALSE`, `NULL`, 'String', 1234, -45e-2, 0xF0A1, 0b10110111, `Date` '2022-04-25', `Timestamp` '2022-04-25 05:28:59',  `Binary` 'FA6CB', `Json` '{"name":"John"}'
* Logical operators `NOT` `AND` `OR`
* Arithmetic operators `+` `-` `*` `/` `%`
* Bitwise operators  `&` `|` `~` `^`
* Comparison operators `>` `>=` `<` `<=` `=` `!=` `<>` `IN` `IS TRUE` `IS FALSE` `IS NULL` `IS DISTINCT FROM` `BETWEEN` `LIKE` `ILIKE`
* Concatenate operator `||`
* Conditional operator `CASE WHEN`
* Cast operator  `::` or `CAST`(<value> `AS` <type> `FORMAT` <format>)
* Over 180 scalar and aggregate https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/functions.adoc[functions] (conditional, mathematical, trigonometry, conversion, bitwise...).
* User Defined Function (UDF) support has metadata
* Use of comments to facilitate reading
* Are not case-sensitive, excepted for identifier
* Can be parenthesized to control the precedence order
* Optimized immediately after parsing, so the `5+XYZ+4*2+5` is optimized to `XYZ+18` and has no impact on performance


https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/expression.adoc[Documentation] are work in progress.


## Extends with plugins

Use @FunctionPlugin annotation to create custom function in your plugin. 

----
/** 
 * The function compute Levenshtein distance.
 */
@FunctionPlugin
public class Levenshtein extends Function {

  public Levenshtein() {
    super("LEVENSHTEIN", true, ReturnTypes.INTEGER, OperandTypes.STRING_STRING, OperatorCategory.STRING, "/docs/levenshtein.html");
  }
  
  @Override
  public Object eval(final IExpressionContext context, final IExpression[] operands)
      throws Exception {
    String str1 = operands[0].getValue(context, String.class);
    if (str1 == null)
      return null;
    String str2 = operands[1].getValue(context, String.class);
    if (str2 == null)
      return null;

    return Long.valueOf(StringUtils.getLevenshteinDistance(str1, str2));
  }
}
----

## How to install

### System Requirements

https://hop.apache.org[Apache Hop] 2.2 or above.
Web Hop is not supported because expression editor use JFace.

### Manual Install

1. Place the expression folder in the hop\plugins\transforms directory
2. Restart Hop

### Support

This plugin is provided as is, without any warranties, expressed or implied. This software is not covered by any Support Agreement.

### License

Licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0].
