/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.hop.expression.jit;

import java.io.StringWriter;
import org.apache.hop.expression.ErrorCode;
import org.apache.hop.expression.ExpressionException;
import org.apache.hop.expression.IExpression;
import org.apache.hop.expression.IExpressionContext;
import org.apache.hop.expression.IExpressionVisitor;
import org.apache.hop.expression.Kind;
import org.apache.hop.expression.Operator;
import org.apache.hop.expression.type.Type;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Wraps an {@link IExpression} whose evaluation has been JIT-compiled by {@link JitCompiler}.
 *
 * <p>Every method delegates to the original, interpreted expression except {@link #getValue()}
 * and {@link #getValue(Class)}, which run the generated bytecode instead. The original tree is
 * kept around (rather than discarded) because it is still needed for {@code unparse}/{@code
 * toString} (e.g. to display the expression in the UI) and for {@link #accept}, which lets other
 * visitors (such as a future JIT re-compilation after a pipeline change) keep working unmodified.
 */
@NullMarked
final class JitCompiledExpression implements IExpression {

  private final IExpression original;
  private final IJitExpression compiled;

  JitCompiledExpression(IExpression original, IJitExpression compiled) {
    this.original = original;
    this.compiled = compiled;
  }

  @Override
  public Kind getKind() {
    return original.getKind();
  }

  @Override
  public Type getType() {
    return original.getType();
  }

  @Override
  public boolean isOperator(Operator operator) {
    return original.isOperator(operator);
  }

  @Override
  public boolean isNull() {
    return original.isNull();
  }

  @Override
  public boolean isConstant() {
    return original.isConstant();
  }

  @Override
  public int getCost() {
    return original.getCost();
  }

  @Override
  public @Nullable Object getValue() {
    try {
      return compiled.eval();
    } catch (ExpressionException e) {
      throw e;
    } catch (Exception e) {
      throw new ExpressionException(ErrorCode.CALL_OPERATOR_ERROR, original, e.getMessage());
    }
  }

  @Override
  public @Nullable <T> T getValue(Class<T> clazz) {
    return getType().convert(getValue(), clazz);
  }

  @Override
  public void validate(IExpressionContext context) throws ExpressionException {
    original.validate(context);
  }

  @Override
  public <E> E accept(IExpressionVisitor<E> visitor) {
    return original.accept(visitor);
  }

  @Override
  public void unparse(StringWriter writer, int leftPrec, int rightPrec) {
    original.unparse(writer, leftPrec, rightPrec);
  }

  @Override
  public String toString() {
    return original.toString();
  }
}
