/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.hop.expression.jit;

import java.math.BigDecimal;
import org.apache.hop.expression.ErrorCode;
import org.apache.hop.expression.ExpressionException;
import org.apache.hop.expression.Operator;
import org.apache.hop.expression.type.Type;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Static helpers invoked by the Java source code generated by {@link JitCodeGenerator}.
 *
 * <p>Each method mirrors exactly the semantics of the corresponding {@link
 * org.apache.hop.expression.Operator#eval} implementation it replaces, so that the interpreted and
 * JIT-compiled evaluation paths always agree. Keeping this logic in one place, rather than
 * inlining it into generated source, keeps the generator simple and lets these methods be unit
 * tested directly.
 */
@NullMarked
public final class JitRuntime {

  private JitRuntime() {}

  public static @Nullable Object addLong(@Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    try {
      return Math.addExact((Long) left, (Long) right);
    } catch (ArithmeticException e) {
      throw new ExpressionException(ErrorCode.ARITHMETIC_OVERFLOW, "+");
    }
  }

  public static @Nullable Object subtractLong(@Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    try {
      return Math.subtractExact((Long) left, (Long) right);
    } catch (ArithmeticException e) {
      throw new ExpressionException(ErrorCode.ARITHMETIC_OVERFLOW, "-");
    }
  }

  public static @Nullable Object multiplyLong(@Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    try {
      return Math.multiplyExact((Long) left, (Long) right);
    } catch (ArithmeticException e) {
      throw new ExpressionException(ErrorCode.ARITHMETIC_OVERFLOW, "*");
    }
  }

  public static @Nullable Object addNumber(@Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    return ((BigDecimal) left).add((BigDecimal) right);
  }

  public static @Nullable Object subtractNumber(@Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    return ((BigDecimal) left).subtract((BigDecimal) right);
  }

  public static @Nullable Object multiplyNumber(@Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    return ((BigDecimal) left).multiply((BigDecimal) right, Operator.MATH_CONTEXT);
  }

  public static @Nullable Object divideNumber(@Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    BigDecimal divisor = (BigDecimal) right;
    if (divisor.signum() == 0) {
      throw new ExpressionException(ErrorCode.DIVISION_BY_ZERO);
    }
    return ((BigDecimal) left).divide(divisor, Operator.MATH_CONTEXT);
  }

  public static @Nullable Object and(@Nullable Object left, @Nullable Object right) {
    if (left == Boolean.FALSE || right == Boolean.FALSE) {
      return Boolean.FALSE;
    }
    if (left == null || right == null) {
      return null;
    }
    return Boolean.logicalAnd((Boolean) left, (Boolean) right);
  }

  public static @Nullable Object or(@Nullable Object left, @Nullable Object right) {
    if (left == null) {
      if (Boolean.TRUE.equals(right)) return Boolean.TRUE;
      return null;
    }
    if (right == null) {
      if (Boolean.TRUE.equals(left)) return Boolean.TRUE;
      return null;
    }
    return Boolean.logicalOr((Boolean) left, (Boolean) right);
  }

  public static @Nullable Object not(@Nullable Object value) {
    if (value == null) return null;
    return !((Boolean) value);
  }

  public static @Nullable Object compareEqual(
      Type type, @Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    return type.compareEqual(left, right);
  }

  public static @Nullable Object compareNotEqual(
      Type type, @Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    return !type.compareEqual(left, right);
  }

  public static @Nullable Object compareLess(
      Type type, @Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    return type.compare(left, right) < 0;
  }

  public static @Nullable Object compareLessOrEqual(
      Type type, @Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    return type.compare(left, right) <= 0;
  }

  public static @Nullable Object compareGreater(
      Type type, @Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    return type.compare(left, right) > 0;
  }

  public static @Nullable Object compareGreaterOrEqual(
      Type type, @Nullable Object left, @Nullable Object right) {
    if (left == null || right == null) return null;
    return type.compare(left, right) >= 0;
  }
}
