////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= ADD_HOURS

Adds or subtracts a specified number of hours to a date or timestamp.
		
== Syntax

----
ADD_HOURS( timestamp, integer )
----

== Returns

Date

== Usage

* Decimals are rounded before adding that number.
* The number of hours, can be a positive or negative integer to either add or subtract hours, respectively.
* Returns NULL if one of the arguments is NULL.

== Examples

----
ADD_HOURS(TIMESTAMP '2024-02-18 22.58.59', 4) return 2024-02-19 02.58.59
----