////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= ARRAY_POSITION

Return a 1-based index of the first occurrence of an element in the input array.
Optionally, starts searching at the specified index.
 
== Syntax
----
ARRAY_POSITION( array, element [, index]  )
----

Return:: Integer

== Usage

* The first position in the array is 1.
* The optional third parameter specifies the inclusive index value at which to start the search.
* Returns NULL if one of the arguments is NULL.
* If the value is not contained in the ARRAY, the function returns NULL.

== Example

----
ARRAY_POSITION(['sun','mon','tue','wed','thu','fri','sat'],'mon') = 2
----