////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= ARRAY_PREPEND

Returns an array concatenating an element to the beginning of an array.
 
== Syntax

----
ARRAY_PREPEND( element, array  )
----

== Arguments

array:: The array to prepend to.
element:: The element to prepend to the array.

== Returns

Returns an array.

== Usage

* Returns NULL if the array is NULL.

== Examples

----
ARRAY_PREPEND(0,[1,2,3]) = [0,1,2,3]
----