////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= ARRAY_SLICE

Returns an array constructed from a specified subset of elements of the input array.

== Syntax
----
ARRAY_SLICE( array, from, to )
----

== Return

This function returns an ARRAY.

== Usage

* Returns NULL if one of the arguments is NULL.
* A negative position is interpreted as an index from the back of the array. 
* If both of the of the `from` or `to` parameters are beyond the upper or lower end of the array, the result is an empty array.

== Examples

----
ARRAY_SLICE([0,1,2,3,4,5,6], 0, 2)
----