////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= BETWEEN

Determines whether the value of one expression is in an interval defined by two other expressions.

== Syntax

----
expression [NOT] BETWEEN [ASYMMETRIC|SYMMETRIC] lower_bound AND upper_bound
----

== Returns

Boolean

== Usage

The ASYMMETRIC keyword is just a verbose way of expressing the default behaviour that upper boundary must be greater than the lower boundary,
SYMMETRIC has the useful property of indicating that the order is irrelevant

== Examples

The following statements are all equivalent: 
----
A BETWEEN SYMMETRIC B AND C
(A BETWEEN B AND C) OR (A BETWEEN C AND B)
(A >= B AND A <= C) OR (A >= C AND A <= B)
----