////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= CAST, TRY_CAST, ::

Converts a value of one data type into another data type.

== Syntax

----
CAST( value AS type [ FORMAT format ] )
TRY_CAST( value AS type [ FORMAT format ] )
----
The xref:concat.adoc["::",role=op] operator provides alternative syntax.
----
value::type
----

== Usage

If the cast is not possible, CAST raises an error and TRY_CAST return a NULL value.

=== Supported data type:

* Binary
* Boolean
* Date
* Inet
* Integer
* Interval
* Number
* String
* Json


=== Rules

* When converting a number to a boolean, 0 is false and every other value is true. 
* When converting a boolean to a number, false is 0 and true is 1. 
* When converting a number to a number of another type, the value is checked for overflow. 
* When converting a string to binary, it is hex encoded (every byte two characters).
* When converting an integer to date, result is the number of seconds that have elapsed since the epoch (00:00:00 UTC on January 1, 1970).
* When converting a number to date, result is the number of seconds that have elapsed since the epoch (00:00:00 UTC on January 1, 1970) and the fractions are nanoseconds.
* When converting a date to integer, result is the number of seconds that have elapsed since the epoch (00:00:00 UTC on January 1, 1970).
* When converting a date to number, result is the number of seconds that have elapsed since the epoch (00:00:00 UTC on January 1, 1970) and the fractions are nanoseconds.

=== Format


== Examples

----
CAST('yes' AS BOOLEAN) result TRUE

// if the cast is not possible, a NULL value is returned.
TRY_CAST('-1234.56' AS INTEGER FORMAT '###0'))

'-1234.56'::INTEGER result -1235

CAST('-1234.56' AS NUMBER FORMAT '###0.00')

CAST('24/05/2020 00:00:00' AS DATE FORMAT 'DD/MM/YYYY HH:mm:ss') result date 2020-05-24

TRY_CAST(MAKE_DATE(2020,5,24) AS STRING FORMAT 'yyyy-q')

----

== See also 

* xref:to_binary.adoc["TO_BINARY",role=fun] 
* xref:to_boolean.adoc["TO_BOOLEAN",role=fun]
* xref:to_char.adoc["TO_CHAR",role=fun]
* xref:to_date.adoc["TO_DATE",role=fun]
* xref:to_interval.adoc["TO_INTERVAL",role=fun]
* xref:to_json.adoc["TO_JSON",role=fun]
* xref:to_number.adoc["TO_NUMBER",role=fun]
