////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:language: en_US
= DECODE

Compares the select expression to each search expression in order. As soon as a search expression matches the selection expression, the corresponding result expression is returned.

== Syntax

----
DECODE( expr, search1, result1 [, search2, result2... ] [, default ] )
----

== Arguments

expr::	This is the select expression.
searchN:: The search expressions indicate the values to compare to the select expression. 

== Usage

If an optional default is specified, and if none of the search expressions match the select expression, then DECODE returns this default value.


TIP: Contrary to `CASE`, a NULL value in the select expression matches a NULL value in the search expressions.

== Examples
----
DECODE(EXTRACT(dayofweek FROM CURRENT_DATE()),
1, 'Monday',
2, 'Tuesday',
3, 'Wednesday',
4, 'Thursday',
5, 'Friday',
6, 'Saturday',
7, 'Sunday')
----