////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= ERROR

Throws the given error message and abort execution of the pipeline or workflow.

== Syntax

----
ERROR( message )
----

== Usage

* Use ERROR within an CASE or DECODE function to set rules for aborting a pipeline.

== Examples

----
DECODE(value,1,'Flag 1',2,'Flag 2',ERROR('Unsupported value'))
----