////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Expression

An expression is a combination of one or more literal values, resolvable identifiers, operators and functions that evaluate to a value.

- Can be parenthesized to control the precedence order.
- Are not case-sensitive, excepted for identifier.
- Optimized immediately after parsing, so the `XYZ+24*60+5` is optimized to `XYZ+1445` and has no impact on performance.

== Comments

Comments are sections of code text to aid readability.


----
// Single line-comment <1>

-- Single line-comment <1>

/* 
 * Multi line	<2>
 * comment /* with nested block */
 */
----

<1> A single line comment begins with two consecutive slash // or hyphen -- characters and ends with a new line.

<2> A multi line comment begins with a slash asterick /* and ends with asterick slash and support nested block comment.

NOTE: A comment is removed when parsing expression before evaluation, therefore has no influence on performance.


== Literals

The simplest kind of expression is a literal that directly represents a constant value.
The following types of literals can be used in expression.

=== String

String literals are always surrounded by single quotes `'`.

----
'test value'
'O''Reilly' <1>
'O' || CHR(13) || 'Reilly' <2>
----
<1> The simplest method to escape single quotes in expression is to use two single quotes.
<2> Use function https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/chr.adoc[CHR] to add special characters.

=== Boolean

Boolean literals are `TRUE` and `FALSE`, with no quotation marks and case-insensitive.
----
TRUE
false
----

=== Integer

Integer literals can be either positive numbers or negative numbers, but do not contain decimals.
Integer are between -9223372036854775808 and 9223372036854775807.
Support hexadecimal, octal, and binary notations and can have embedded underscore `_` characters to improve readability.

Decimal integers are a sequence of decimal digits [0-9].
----
013
536
+536
-536
1_500_000_000
----

Hexadecimal integers are a sequence of hexadecimal digits [0-9A-Fa-f] preceded by a `0x` or `0X`. 
----
0xAE
0X12Ef
0xFF69_048A_EFDD_010E
----

Octal integers are a sequence of octal digits [0-7] preceded by a `0o` or `0O`. 
----
0o1234567
0O123_4567
----

Binary integers are a sequence of binary digits [0-1] preceded by a `0b` or `0B`. 
----
0b1000001011110
0B1_0000_0101_1110
0b_1001_0001
----

NOTE: A numeric literal that is outside the range of the INTEGER type is assigned to NUMBER(n, 0), where n is the number of digits in the literal, excluding leading zeros. 

NOTE: The use of underscores is restricted to one underscore between digits or prefixes.

=== Number

Literals can be either positive numbers or negative numbers and contain decimals. 

The precision of a number is the total count of significant digits in the whole number, that is, the number of digits to both sides of the decimal point. The scale of a number is the count of decimal digits in the fractional part, to the right of the decimal point.
The maximum supported precision is 38.

----
24.7
+0.5
-24.7
3e2
0.5E-2
1e10
1_000.123e-1_0
----

NOTE:
* In addition, scientific notation can be used.
* The decimal point must be represented by a period. A comma is not recognized as a valid decimal point.
* Can have embedded underscore `_` characters to improve readability (Leading, trailing and double underscores will produce an error).
* There is no literal representation of NaN or infinity.

=== Binary

Binary literals of the word BINARY followed by a hexadecimal notation (2 hexadecimal digits per byte) surrounded by single quotes `'`.

The following examples illustrate some binary values:
----
BINARY 'ac6F'
BINARY '4b657276656E'
----

=== Date

Date literals consist of the word DATE followed by a 10 characters string literal enclosed in apostrophes in a `YYYY-MM-DD` format. 

The following examples illustrate some date values:
----
DATE '2020-05-18'
'2020-05-18'::DATE
----

The parsing is strict and requires months to be less than 12, days to be less than 31.

=== Timestamp


Literal timestamp can includes a time zone offset or a time zone region.

----
TIMESTAMP 'yyyy-mm-dd hh24:mi:ss.ffffff' [AT TIME ZONE  '...']
----
The following examples illustrate some timestamp values:
----
TIMESTAMP '2020-05-18 23:48'
TIMESTAMP '2020-05-18 23:48:59'
TIMESTAMP '2020-05-18 23:48:59.123456789'
TIMESTAMP '2020-05-18 23:48:59 +05:00'
TIMESTAMP '2020-05-18T23:48:59+0500'
TIMESTAMP '2021-01-01 15:28:59' AT TIME ZONE 'US/Pacific'
----

In some of the timestamp formats, the letter T is used as a separator between the date and time.

The UTC offset form can be further refined to include the regional time zone, ensuring consistency of local time calculations while observing daylight saving time.

NOTE: Time zone names are case-sensitive and must be enclosed in single quotes (e.g. 'UTC'). A time zone name is valid if recognized by Java’s ZoneId.of.

=== Interval

Interval literals defines a constant time period. You can use interval to add or subtract a period of time to/from a date or timestamp.

----
INTERVAL 1 YEAR
INTERVAL 5 DAYS
INTERVAL -12 HOURS
INTERVAL '2 MONTHS 5 DAYS 12 HOURS'
INTERVAL '+2-6' YEAR TO MONTH
INTERVAL '10 23:30:58.999' DAY TO SECOND
----

Interval constants can also be expressed using the following formats: 
	INTERVAL 'Y-M D H:M:S.FFFFFFFFF'
	INTERVAL 'Y-M' YEAR TO MONTH
	INTERVAL 'D H:M:S.FFFFFFFFF' DAY TO SECOND
	INTERVAL 'H:M' HOUR TO MINUTE

==== Short format:
----
{ + | - } INTERVAL '<format>' [ <qualifier> ]
----

* `format` the full format is 'Y-M D H:M:S.FFFFFFFFF' but with qualifier DAY TO MINUTE format is 'D H:M'
* `qualifier` can be any of YEAR, MONTH, DAY, HOUR, MINUTE, SECOND, YEAR TO MONTH, DAY TO HOUR, DAY TO MINUTE, DAY TO SECOND, HOUR TO MINUTE, HOUR TO SECOND, MINUTE TO SECOND
* If the qualifier is not a range (<unit> TO <unit>), the single quote can be omitted.



The following examples illustrate some interval values that use the short syntax:
----
INTERVAL 2 MONTHS
INTERVAL '4-2' YEAR TO MONTH
INTERVAL '15 04:30' DAY TO MINUTE
INTERVAL '-1-3 10 23:30:58.999'
----

==== Verbose format:

----
{ + | - } INTERVAL '<quantity> [ <unit> ] [, <quantity> [ <unit> ] ... ]'
----

* `quantity` is a number
* `unit` can be any of YEAR, QUARTER, MONTH, WEEK, DAY, HOUR, MINUTE, SECOND, MILLISECOND, MICROSECOND or plural forms (MONTHS, DAYS, etc.).

The following examples illustrate some interval values that use the verbose syntax:
----
INTERVAL '2 MONTHS, 5 DAYS, 12 HOURS'
INTERVAL '4 WEEKS'
----


The following subtracts 4 months from March 31, 2023 and the result is November 30, 2022. The calculation considers the number of days in a month.
----
DATE '2023-03-31' - INTERVAL 4 MONTHS
----


=== Json

Literal json.

----
JSON '{"name":"John","age":30}'
----


== Identifier

Identifiers are the names of fields and is case-sensitive. 

The field name can be enclosed in double quotes `"` such as `"Employee Name"`, this would allow identifiers to contain spaces, other punctuation, and to be keywords.

For example, `YEAR` cannot be used whereas `"YEAR"` can be accepted. 

NOTE: If you wish to include a double quote in an identifier, use another double quote to escape it.

== Operator

Expression supports most of the arithmetic, bitwise, logical and comparison operators.


The operator precedence and associativity, highest to lowest.

[cols="^1,<5,<5", options="header"]
|===
|Associativity|Operator|Description
|left|()|Parenthesis
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/functions.adoc[function](args...)|Function
|right|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/cast.adoc[::]|Cast
|right|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/cast.adoc[[]]|Array element selection
|right|+, -|Positive, Negative
|right|~|Bitwise NOT
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/multiply.adoc[*], https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/divide.adoc[/], %|Multiplication, Division, Modulus
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/add.adoc[+], https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/subtract.adoc[-]|Addition, Subtraction
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/concat.adoc[\|\|]|Concatenation
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/bit_and.adoc[&]|Bitwise AND
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/bit_xor.adoc[&circ;]|Bitwise XOR (exclusive OR)
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/bit_or.adoc[\|]|Bitwise OR (inclusive OR)
|left|
https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/is-null.adoc[IS NULL],
https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/is-true.adoc[IS TRUE],
https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/is-false.adoc[IS FALSE],
https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/is-distinct-from.adoc[IS DISTINCT FROM]|Conditional
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/in.adoc[IN]|Membership
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/between.adoc[BETWEEN]|Range containment
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/like.adoc[LIKE], https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/ilike.adoc[ILIKE],  https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/similarto.adoc[SIMILAR TO]|Pattern matching
|left|=, >, <, >=, <=, <>, != |Comparison
|right|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/boolnot.adoc[NOT]|Logical negation 
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/booland.adoc[AND]|Logical conjunction
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/boolxor.adoc[XOR]|Logical exclusive disjunction 
|left|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/boolor.adoc[OR]|Logical disjunction 
|===

NOTE: An operator on higher levels is evaluated before an operator on a lower level. You can enclose an expression in parentheses to force precedence or clarify precedence, for example, (5 + 2) * 3.

NOTE: When an operator combines expressions of different data types, the data type with the lower precedence is first converted to the data type with the higher precedence. If the conversion isn't a supported implicit conversion, an error is returned. 

== Type coercion

Expression supports both implicit and explicit conversion between data types.

Explicit conversion is supported by using the `CAST` function or specific functions.

When there is no ambiguity about the data type of an expression value, it is implicitly coerced to match the expected data type.

[cols="^5,^1,^1,^1,^1,^1,^1,^1,^1", options="header"]
|===
|From / To|Binary|Boolean|Date|Integer|Number|String|Json|Inet
|Function|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/to_binary.adoc[TO_BINARY]|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/to_boolean.adoc[TO_BOOLEAN]|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/to_date.adoc[TO_DATE]||https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/to_number.adoc[TO_NUMBER]|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/to_char.adoc[TO_CHAR]|https://github.com/nadment/hop-expression/blob/master/plugins/src/main/doc/to_json.adoc[TO_JSON]|
|Binary|-|❌|❌|❌|❌|✅|❌|❌
|Boolean|❌|-|❌|✅|✅|✅|❌|❌
|Date|❌|❌|-|☑️|☑️|✅|❌|❌
|Integer|❌|✅|☑️|-|✅|✅|❌|❌
|Number|❌|✅|☑️|☑️|-|✅|❌|❌
|String|☑️|☑️|☑️|☑️|☑️|-|☑️|❌
|Json|❌|❌|❌|❌|❌|✅|-|❌
|Inet|❌|❌|❌|❌|❌|✅|❌|-
|===

❌ Non convertible
✅ Coerce: Implicit conversion
☑️ Cast: Explicit conversion

* Numeric types can be coerced to a wider numeric type. For example, an INTEGER type can be coerced to a NUMBER.



