////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= FIRST_VALUE [aggregate]

Returns the first value in an ordered set of values over a group of rows.

== Syntax
----
FIRST_VALUE( expression ) [ IGNORE NULLS | RESPECT NULLS ]
----

== Returns

The data type of the returned value is the same as the data type of the input values.

== Usage

* If the first value in the set is null, then the function returns NULL unless you specify `IGNORE NULLS`.

* If `IGNORE NULLS` or `RESPECT NULLS` is not specified, the default is `RESPECT NULLS`

NOTE: This is an analytic function that should only be used in the Aggregate transformation.

== Example

----
FIRST_VALUE( City ) IGNORE NULLS
----

== See also

* xref:last_value.adoc[LAST_VALUE]
* xref:nth_value.adoc[NTH_VALUE]