////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= IS DISTINCT FROM

Compares whether two expressions are equal or not equal. The operator is NULL-safe, meaning it treats NULLs as known values for comparing equality. Note that this is different from the EQUAL comparison	operator xref:equal.adoc["=",role=op], which treats NULLs as unknown values.

== Syntax

----
expression1 IS [NOT] DISTINCT FROM expression2
----

== Returns

Boolean

== See also

* xref:equal.adoc["=",role=op]
* xref:equal_null.adoc["EQUAL_NULL",role=fun]
