////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= JSON_OBJECT

Generates a JSON object by using the specified key:value pairs.

== Syntax
----
JSON_OBJECT([KEY] key1 VALUE value2 [, [KEY] key2 VALUE value2, ...])
----

== Returns

JSON object containing all the key-value pairs.

== Usage

* `KEY` is optional and is provided for semantic clarity.
* If there are duplicate key-value pairs in the parameters, the last key-value pairs are retained in the final returned object.

== Examples

----
VALUES JSON_OBJECT(KEY 'first' VALUE 'John', KEY 'last' VALUE 'Doe')
----