////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= JSON_KEYS

Extracts unique JSON keys from a JSON expression.

== Syntax

----
JSON_KEYS( {string | json} [, path] )
----

== Returns

Array of String

== Usage

* The path must begin with a dollar sign `$`, which represents the root. 
* Returns `NULL` if any of the arguments are null, a given path does not locate an object, or if the JSON argument is not an object.
* If the JSON object has no keys, an empty array is returned.
* Keys are de-duplicated and returned in alphabetical order.
* Keys are case-sensitive.

include::jsonpath.adoc[]

== Examples

----
JSON_KEYS(JSON '{"a": 1, "b": {"c": 30}}') >>> ['a','b']
JSON_KEYS(JSON '{"a": 1, "b": {"c": 30}}','$') >>> ['a','b']
JSON_KEYS(JSON '{"a": 1, "b": {"c": 30}}','$.b') >>> ['c']
JSON_KEYS(JSON '{"b": 1, "a": 1, "c": 30, "a": 2}') >>> ['a','b','c']
JSON_KEYS(JSON '{}') >>> []
----