////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= JSON_QUERY

Extracts a JSON fragment from a JSON object by using JsonPath query language.

== Syntax

----
JSON_QUERY( json [, path] )
----

== Arguments

json:: JSON value or a JSON-formatted string

path:: A xref:jsonpath.adoc[JsonPath] expression that identifies the data that you want to get

== Returns

Json

== Usage

* The path must begin with a dollar sign `$`, which represents the root. 
* If the path does not match a value, `NULL` is returned.

include::jsonpath.adoc[]

== Examples

----
JSON_QUERY('{"language":["English", "French"]}','$.language') return [English, French]
----