////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

== JsonPath query language

These are the supported operators from the JsonPath standard.

[cols="^1,<5", options="header"]
|===
|Operator|Description
|`$`|The root element 
|`@`|The current element being processed by a filter predicate.
|`*`|All elements regardless their names
|`.name`|Child property with dot notation
|`..name`|Child property at any level deeper
|[`number`, `number`]|Array index or indexes
|[`start`:`end`)]|Array slice operator
|?(`expression`)|Filter expression (Expression must evaluate to a boolean value).
|===

NOTE: JsonPath is case-sensitive.