////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= LPAD

Left-pads a string with characters from another string, or right-pads a binary value with bytes from another binary value.

== Syntax

----
LPAD( value, length [, pad ] )
----

Returns:: The data type of the returned value is the same as the data type of the input value (`STRING` or `BINARY`).

== Usage 

* Both value and pad must be of the same string or binary type.
* If the length argument is smaller than the value, the function will truncate the string to the size of length.
* If the padding argument is omitted, the function will pad spaces for string or 0x00 for binary.
* Returns NULL if one of the arguments is NULL.

== Example

----
LPAD('123',5,'*') = '**123'
----

See also xref:rpad.adoc[RPAD]