////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= OVERLAY

Replaces a substring of the specified length, starting at the specified position, with a new string.
 
== Syntax
----
OVERLAY( value, replace, position [, length] )
----

Returns:: String

== Usage

* The first position in the string is 1.
* If `position` is beyond the end of string, replacement is placed directly after string.
* If `length` is 0, `replace` is simply inserted.
* If `length` is omitted, it defaults to the length of replace.
* Returns NULL if one of the arguments is NULL.

== Example

----
OVERLAY('Apxxxe','ach',3) = 'Apache'
OVERLAY('Apxxxe','ache',3,2) = 'Apacxe'
OVERLAY('Apxxxe','pl',3,3) = 'Apple'
----