////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= PARSE_URL

Returns the specified part of the URL or the value for the specified QUERY key.

== Syntax
----
PARSE_URL(url, part [, key]) 
----

Return:: String

== Usage

* `part` must be one of HOST, PORT, PATH, QUERY, REF, PROTOCOL, FRAGMENT, AUTHORITY, FILE, USERINFO.
* Use `key` specifies which query to extract (case-sensitive).
* If a requested part or key is not found, NULL is returned.
* Returns NULL if one of the arguments is NULL.

== Examples

----
PARSE_URL('https://hop.apache.org:80/path?id=1','HOST') → hop.apache.org
PARSE_URL('https://hop.apache.org:80/path?id=1','PATH') → /path
PARSE_URL('https://hop.apache.org:80/path?id=1&lang=fr','FILE') → /path?id=1&lang=fr
PARSE_URL('https://hop.apache.org:80/path?id=1&lang=fr','QUERY') → id=1&lang=fr
PARSE_URL('https://hop.apache.org:80/path?id=1&lang=fr','QUERY','id') → 1
PARSE_URL('https://hop.apache.org:80/path?id=1#fragment','FRAGMENT') → fragment
----