////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= PERCENTILE [aggregate]

Returns the percentile of values at the specified percentage over a group of rows.

== Syntax

----
PERCENTILE( expression, percentage )
----

expression:: An expression that evaluates to a numeric.
percentage:: A numeric expression between 0 and 1 

Return:: Number

== Usage

* Null values are ignored.

NOTE: This is an analytic function that should only be used in the Aggregate transformation.

== Examples

----
PERCENTILE( Age, 0.25 )
----

