////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= REGEXP_INSTR

Searches a string using a regular expression pattern and returns an integer that indicates the beginning
position or ending position of the matched substring. 

== Syntax

----
REGEXP_INSTR( subject, pattern [, position [, occurrence [, return_options [, parameters ]]]] )
----

<source>:: The string to be searched for.
<pattern>:: The regular expression pattern.
<replacement>:: The string that replaces the matched pattern. This argument is optional. Default value is ''.
<position>:: The position in the source string where the search starts. This argument is also optional. Default value is 1. 
<occurrence>:: Specifies which occurrence of the pattern to replace. This argument is also optional. If 0 is specified, all occurrences are replaced. Default value is 0 (all occurrences)
<parameters>:: One or more string literals that indicate how the function matches the pattern.
* `c` Case-sensitive matching.
* `i` Case-insensitive matching.
* `m` Multi-line mode.
* `n` allows the period (.) which is the match-any-character character, to match the newline character. 

Return type:: Integer

== Usage

* If no match is found, then the function returns 0.
* The <pattern> is defined according to Java language regular expression rules. 