////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= SIMILAR TO

Match a string based on a regular expression pattern.

== Syntax
----
subject [NOT] SIMILAR TO pattern
----

== Arguments

subject:: The string to be searched for.
pattern:: The regular expression pattern.

== Returns

Boolean

== Usage

* Returns true only if its pattern matches the entire string.
* Performs a case-sensitive match.

Regular expression pattern

[cols="<1,<1",options="header"]
|===
|Operator|Description
|%|Matches any sequence of zero or more characters.
|_|Matches any single character.
|\||Denotes alternation (either of two alternatives).
|*|Repeat the previous item zero or more times.
|+|Repeat the previous item one or more times.
|?|Repeat the previous item zero or one time.
|+{m}+|Repeat the previous item exactly m times.
|{m,}|Repeat the previous item m or more times.
|{m,n}|Repeat the previous item at least m and not more than n times.
|()|Parentheses group items into a single logical item.
|[...]|A bracket expression specifies a character class, just as in POSIX regular expressions.
|===

== Examples

----
'xyz' SIMILAR TO '%(y|a)%'
----