////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= STRTOK

Splits a string on the specified list of delimiter characters and returns the part at the specified position.

== Syntax
----
STRTOK( string [, delimiters ] [, part ] )
----

string:: A string expression to be tokenized.
delimiters:: Each character in the string is considered a delimiter character. If not specified, the default is a space character.
part:: The ordinal token to return. If not specified, the default value is 1. The maximum limit of any token returned is 256.

Returns:: String

== Usage

* If the string starts or is terminated with the delimiter, the function considers empty space before or after the delimiter, respectively, as a valid token.
* Adjacent delimiters are treated as delimiters for empty tokens.
* If any parameter is NULL, then NULL is returned.

TIP: Use SQUEEZE function to remove start, end or adjacent delimiters.