////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= TO_DATE, TRY_TO_DATE

Converts a string into a date or the epoch time value to a timestamp with UTC time zone.

== Syntax

----
TO_DATE( string [, format ] )
TRY_TO_DATE( string [, format ] )
TO_DATE( numeric )
TRY_TO_DATE( numeric )
----

== Returns

Date

== Usage

If the conversion is not possible, TO_DATE raises an error and TRY_TO_DATE returns a NULL value. 

include::dateformat.adoc[]

* An element in the date format model can only appear once. However, elements such as separators, padding characters can appear more than once.
* If no format is specified, the standard format YYYY-MM-DD is used to interpret string.
* Timezones are case sensitive, Europe/London is not the same as europe/london.
* If single elements are omitted, then their minimum values are assumed (for example, TO_DATE('1999-12', 'YYYY-MM') is interpreted as December 1st, 1999).
* If a match fails between a format element and the corresponding characters in the string, then expression attempts alternative format.
[cols="<2,<5", options="header"]
|===
|Original format|Try alternative format elements
|MM|MON and MONTH
|MON|MONTH  
|MONTH|MON 
|===

If used with numeric value, the value is the number of seconds that have elapsed since the epoch (00:00:00 UTC on January 1, 1970) and the fractions are nanoseconds.

== Examples

----
TO_DATE('2019-02-13 15:34:56 +08:00','YYYY-MM-DD HH24:MI:SS TZH:TZM')
TO_DATE(1284352323.123) result 2010-09-13 04:32:03.123 
TO_DATE(1284352323.000000123) result 2010-09-13 04:32:03.000000123 
----

See also xref:make_date.adoc[MAKE_DATE], xref:make_timestamp.adoc[MAKE_TIMESTAMP]