////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= TRY

The function ensures that errors during expression evaluation result in NULL instead of causing an error.

== Syntax

----
TRY( expression )
----

== Arguments

expression:: A string expression

== Returns

The data type of the returned value is the same as the data type of the expression.

== Usage

* Returns NULL if argument is NULL. 

== Examples

The following calls return errors when invoked without the TRY expression. When they are wrapped into as TRY expression, they return NULL:

----
TRY(5/0) return NULL
TRY('abc'::INTEGER) return NULL
TRY(LN(0)) return NULL
----