////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= ADD_WEEKS

This function adds or subtracts a specified number of weeks to a date or timestamp.
		
== Syntax
----
ADD_WEEKS(<date_or_timestamp>, <integer>)
----

== Usage

* Decimals are rounded before adding that number.
* The number of weeks, can be a positive or negative integer to either add or subtract weeks, respectively.