= Expression

An expression is a combination of one or more values, operators and functions that evaluate to a value.

NOTE: Expression is not SQL. It is a proprietary language of data transformation.

== Comments

Comments are sections of code txist to aid readability.

A single -line comment begins with double slash // and ends with a new line.
----
// Single line-comment
----

A multi-line comment begins with a slash asterick /* and ends with asterick slash.
----
/* 
 * Multi line
 * comment 
 */
----

== Literals

The following types of literals (constant values) can be used in expression.

=== String

String literals are always surrounded by single quotes (')
----
'test value'
'O''Reilly'
----
TIP: The simplest method to escape single quotes in expression is to use two single quotes.

=== Boolean

A Boolean constant specifies the keyword TRUE or FALSE.
----
TRUE
FALSE
----

=== Integer

Integer literals can be either positive numbers or negative numbers, but do not contain decimals.
----
536
+536
-536
----

=== Number

Literals can be either positive numbers or negative numbers and contain decimals. In addition, scientific notation can be used.
----
24.7
+0.5
-24.7
0.5E-2
----

NOTE: The decimal point must be represented by a period. A comma is not recognized as a valid decimal point.

=== Binary

Binary can be a sequence of hexadecimal digits with 0x prefix.
----
0xAE  
0x12Ef  
0x69048AEFDD010E 
----
Or also be composed by 0 and 1 digits with 0b prefix. 
----
0b00000010
----

NOTE: They are not enclosed in quotation marks.

TIP: To convert a binary literal into an integer, just add 0.

=== Date

----
Date '2020-05-18'
----
----
Date(2020,5,18)
----


=== Timestamp

----
Timestamp '2020-05-18 23:48:59'
----

== Operator

Expression supports most of the arithmetic, bitwise, logical and comparison operators.



The operator precedence and associativity, highest to lowest.

[cols="^1,<5", options="header"]
|===
|Associativity|Operator
|-|Function
|right| + (Positive), - (Negative)
||~ (Bitwise NOT)
|left|* (Multiplication), / (Division), % (Modulus)
||<<, >>  TODO: Not implemented
||& (Bitwise AND)
||^ (Bitwise Exclusive OR)
||\| (Bitwise OR) 
|left| + (Addition), - (subtraction)
|left| \|\| (Concatenation)
|-|BETWEEN, IN, LIKE, ILIKE
|left|=, >, <, >=, <=, <>, != (Comparison operators) 
|-|IS NULL, IS FALSE, IS NOT TRUE etc.
|right|NOT
|left|AND
|left|XOR
|left|OR
|===

NOTE: An operator on higher levels is evaluated before an operator on a lower level.

== Function

Expression support scalar function.