////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= INSTR

Returns the position in the string that is the first character of a specified occurrence of the substring.
The first position in the string is 1. 
If substring is not found in string, then the INSTR function will return 0.			
If the start_position is negative, the INSTR function counts back start_position number of characters from the end of string and then searches towards the beginning of string.
		

== Syntax
----
INSTR(string, pattern[, start_position])
----