////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= BITROTATE

Rotates the bits for a numeric by the specified number of bits to the left or to the right.

== Syntax
----
BITROTATE( value, distance )
----
value:: This expression must evaluate to a data type that can be cast to Integer.
Return:: Integer

== Usage

* If distance is positive, it will rotate to the left.
* If distance is negative, it will rotate to the right.
* Returns NULL if one of the arguments is NULL.
 