////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= CAST, ::

Converts a value of one data type into another data type:

The :: operator provides alternative syntax.

== Syntax
----
CAST( <value> AS <dataType> [ FORMAT <format> ] )
----
----
<value>::<dataType>
----

== Usage

=== Supported data type:

* BigNumber		
*	Binary
*	Boolean
*	Date
*	Integer
*	Number
*	String

=== Rules

* When converting a number to a boolean, 0 is false and every other value is true. 
* When converting a boolean to a number, false is 0 and true is 1. 
* When converting a number to a number of another type, the value is checked for overflow. 
* When converting a string to binary, it is hex encoded (every byte two characters).

=== Format

If the cast is not possible, an error is raised.

== Examples

----
CAST('yes' AS BOOLEAN)

// if the cast is not possible, an NULL value is returned.
TRY(CAST('-1234.56' AS INTEGER FORMAT '###0'))

'-1234.56'::INTEGER

CAST('-1234.56' AS NUMBER FORMAT '###0.00')

CAST('24/05/2020 00:00:00' AS DATE FORMAT 'DD/MM/YYYY HH:mm:ss')

CAST(Date(2020,5,24) AS STRING FORMAT 'yyyy-q')
----



See also xref:to_boolean.adoc[TO_BOOLEAN], xref:to_char.adoc[TO_CHAR]