////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= COUNT [aggregate]

Returns the number of input values or rows over a group of rows.

== Syntax

----
COUNT( [DISTINCT] expression )
----
----
COUNT( * )
----

Return:: Integer

== Usage

* This is an analytic function that should only be used in the Aggregate transformation.
* COUNT(*) returns the number of items in a group. This includes NULL values and duplicates.
* COUNT(expression) evaluates expression for each row in a group, and returns the number of nonnull values.
* COUNT(DISTINCT expression) evaluates expression for each row in a group, and returns the number of unique, nonnull values.
