////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= DATE_FROM_PARTS

Creates a date from individual numeric components.
		
== Syntax
----
DATE_FROM_PARTS( year, month, day )
----

Returns:: Date

The literal value with ISO format provides alternative syntax.
----
DATE 'YYYY-MM-DD'
----

== Usage

DATE_FROM_PARTS is typically used to handle values in “normal” ranges (e.g. months 1-12, days 1-31), but it also handles values from outside these ranges.

* If day<1 or day>31 then date month is adjusted: Date(2020, 6, 50) >> 2020 JUNE 21
* If month<1 or month>12 then date year is adjusted: Date(2020,19,1) >> 2021 JUNE 01