////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= EXTRACT, DATE_PART

Extracts the specified time unit from a date or timestamp.

== Syntax
[source,sql]
----
EXTRACT( unit FROM {date | timestamp} )
----
[source,sql]
----
DATE_PART( unit, {date | timestamp} )
----

Return type:: Integer

== Usage

[cols="^2,^2,<5", options="header"]
|===
|Unit|Abbreviations or variations|Description
|CENTURY||The century is the year divided by 100
|DAYOFMONTH|DAY|The day of the month (1-31)
|DAYOFWEEK||The day of week (1=Sunday, 2=Monday, 3=Tuesday, 4=Wednesday, 5=Thursday, 6=Friday, 7=Saturday)
|DAYOFYEAR||The day of year (1-365/366)
|DECADE||The decade is the year divided by 10
|EPOCH||The number of seconds since 1970-01-01 00:00:00 UTC
|HOUR||The hour (0-23)
|ISODAYOFWEEK||The day of week following the ISO-8601 standard (1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday, 7=Sunday)
|ISOWEEKOFYEAR|ISOWEEK|The week of year (01-52 or 01-53) based on the ISO-8601 standard. The first week of each ISO year begins on the Monday before the first Thursday of the Gregorian calendar year.
|ISOYEAR||The ISO year of week
|MILLENNIUM||The millennium is the year divided by 1000 
|MILLISECOND||Seconds (and fractional seconds) multiplied by 1,000
|MICROSECOND||Seconds (and fractional seconds) multiplied by 1,000,000
|MINUTE||The minute (0-59)
|MONTH||The month (1-12)
|NANOSECOND||The nanosecond
|QUARTER||The quarter of the year (1-4)
|SECOND||The second (and fractional seconds)
|TIMEZONE_HOUR||The hour of the time zone offset
|TIMEZONE_MINUTE||The minute of the time zone offset
|WEEKOFYEAR|WEEK|The aligned week of year (01-53) where week 1 starts on the first day of the year.
|YEAR||The year

|===

See also functions xref:year.adoc[YEAR], xref:month.adoc[MONTH], xref:day.adoc[DAY], xref:hour.adoc[HOUR], xref:minute.adoc[MINUTE], xref:second.adoc[SECOND]