////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= JAROWINKLER

Returns the Jaro Winkler distance between the two strings.

== Syntax
----
JAROWINKLER( string1, string2 )
----

Return:: Integer

== Usage

* The function returns an integer between 0 and 100, where 0 indicates no similarity and 100 indicates an exact match.
* Information about Jaro Winkler distance can be found here: https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance..