////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= JSON_VALUE

Extracts scalar value from JSON data type or string representing a Json.

== Syntax
----
JSON_VALUE( {string | json}, path )
----

== Usage


path:: Use JSONPath query language for JSON, similar to XPath for XML. The path expression must begin with a dollar sign ($), which represents the context item. The dollar sign is followed by zero or more steps, each of which can be an object step or an array step. JSONPath expressions, including property names and values, are case-sensitive.

== Examples

----
JSON_VALUE('{"language":["English", "French"]}','$.language[1]') >>> French
JSON_VALUE('{"address":{"zip":"12345","city":"Brussels"}}','$.address.zip') >>> 12345
----