////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= LEFT

Extracts a number of characters from a string or bytes from binary starting from left.
		
== Syntax

----
LEFT( value, length )
----

== Usage

* If the length argument is larger than the value, the function will return the value.
* If the length argument is zero or negative, the function returns an empty string or binary.
* Returns NULL if one of the arguments is NULL.

== Example

----
LEFT('ABCDEF',3) = 'ABC'
----

See also xref:right.adoc[RIGHT]