////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= LISTAGG [aggregate]

Returns the concatenated input values over a group of rows, separated by the delimiter string.

== Syntax

----
LISTAGG( [DISTINCT] expression [, delimiter] )
----


Return:: String

== Usage

* Use the `DISTINCT` clause to return only unique values.
* If the input is empty, an empty string is returned.
* If all input expressions evaluate to null, the output is null.

NOTE: This is an analytic function that should only be used in the Aggregate transformation.
