////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= REGEXP_REPLACE

Replace substring in a string by a new substring using a regular expression.

== Syntax
----
REGEXP_REPLACE( <source> , <pattern> [, <replacement> [, <position> [, <occurrence> [, <parameters>]]]] )
----

== Arguments

<source>:: The string to be searched for.
<pattern>:: The regular expression pattern.
<replacement>:: The string that replaces the matched pattern. This argument is optional. Default value is ''.
<position>:: The position in the source string where the search starts. This argument is also optional. Default value is 1. 
<occurrence>:: Specifies which occurrence of the pattern to replace. This argument is also optional. If 0 is specified, all occurrences are replaced. Default value is 0 (all occurrences)
<parameters>:: One or more string literals that indicate how the function matches the pattern.
* `c` Case-sensitive matching.
* `i` Case-insensitive matching.

Return type:: String

== Usage

* If no matches are found, returns the original subject.
* The replacement string can contain backreferences to capture groups. A capture group is a regular expression that is enclosed within parentheses (( )).




