////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= SPLIT_PART

Splits a string on the specified string delimiter and returns the part at the specified position.

== Syntax
----
SPLIT_PART( <string> ,<delimiter> ,<part>} )
----

Returns:: String

== Usage

* If the requested part does not exist, the returned value is an empty string.
* If any parameter is NULL, then NULL is returned.
* If the part number is negative, the parts are counted backward from the end of the string.


== Examples

----
SPLIT_PART('127.0.0.1', '.', 1) return '127'
SPLIT_PART('AAA-@-BBB-BBB-@-CCC','-@-',2) return 'BBB-BBB'
SPLIT_PART('user@hop.apache.org', '.', -2) return 'apache'
SPLIT_PART('127.0.0.1', '', 1) return  '127.0.0.1'
SPLIT_PART('127.0.0.1', NULL, -1) return NULL
----