////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= STRTOK

Splits a string on the specified list of delimiter characters and returns the part at the specified position.

== Syntax
----
STRTOK( <string> [,<delimiters>] [,<part>} )
----

Returns:: String

== Usage

* If the requested part does not exist, then NULL is returned. 
* If any parameter is NULL, then NULL is returned.
* If delimiters is not specified, the default delimiter character is a space character.
* If part number is not specified, the default value is 1.
 