////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= SUBSTRING, SUBSTR

Returns the portion of the string from string, starting from the character/byte specified by start, with optionally limited	length.
		
== Syntax
----
SUBSTRING( <string> , <start> [, <length> ] )
SUBSTR( <String> , <start> [, <length> ] )
----

Return:: String

== Usage

* If length is not specified, all of the characters to the end of the string are used.
* The first character of a string has position 1. If position is negative, counting begins at the end of the string.
* Returns NULL if one of the arguments is NULL. 