////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= TIMESTAMP

Creates a timestamp from individual numeric components.
		
== Syntax
----
TIMESTAMP( year, month, day, hour, minute, second [, nanosecond] )
----
The literal value with ISO format provides alternative syntax.
----
TIMESTAMP 'YYYY-MM-DD HH.MM.SS'
----

== Usage

* If day<1 or day>31 then month is adjusted: Date(2020, 6, 50) >> 2020 JULY 21
* If month<1 or month>12 then year is adjusted: Date(2020,19,1) >> 2021 JULY 01
* If hour<0 or hour>23 then day is adjusted
* If minute<0 or minute>59 then hour is adjusted
* If second<0 or second>59 then minute is adjusted