////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= TO_CHAR

Converts a number, date or timestamp to a string.

== Syntax
----
TO_CHAR( <numeric> [, <format> ] )
----
----
TO_CHAR( <date_or_timestamp> [, <format> ] )
----

== Usage

include::dateformat.adoc[]


include::numberformat.adoc[]


NOTE: Fill mode modifier; toggles between compact and fill modes.

== Format examples
 
[cols="2,2"]
|===
|DY, DD MON YYYY HH12:MI:SS AM|Thu, 21 Dec 2021 04:01:07 PM
|YYYY-MM-DD"T"HH24:MI:SS.FF6TZH:TZM|2021-12-21T04:01:07.123456+02:00
|DD/MM/YYYY HH24:MI TZR|21/12/2021 04:01:07 Europe/Paris
|===