////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= TO_NUMBER, TRY_TO_NUMBER

Converts a string into a number.

== Syntax
----
TO_NUMBER( string [, format ] )
TRY_TO_NUMBER( string [, format ] )
----

Return:: BigNumber

If the conversion is not possible, TO_NUMBER raises an error and TRY_TO_NUMBER returns a NULL value.

== Usage


include::numberformat.adoc[]

=== Alternate formats
When parsing strings, it is possible to specify multiple alternative formats by separating format strings with the | character.
----
TO_NUMBER(1234, 'S9999|9999S')
---- 