////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= TO_BOOLEAN

Converts the input text or numeric expression to a Boolean value.

== Syntax
----
TO_BOOLEAN(text_or_numeric)
----

== Usage

For a text expression, string must be::
* 'true', 't', 'yes', 'y', 'on', '1' return TRUE.
* 'false', 'f', 'no', 'n', 'off', '0' return FALSE.
*  All other strings return an error.

Strings are case-insensitive.

For a numeric expression::
* 0 returns FALSE.
* All non-zero values return TRUE.

