////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= TO_NUMBER

This function converts a string into a number. [DEV IN PROGREES]

== Syntax
----
TO_NUMBER(text [,format])
----

== Usage


[cols="<2,<2,<5", options="header"]
|===
|Element|Repeatable|Description
|. (period)||Decimal fraction separator
|, (comma)|&#10003;|Digit group separator
|0|&#10003;|Leading or trailing zeroes
|9|&#10003;|Digit
|D||Decimal fraction separator (use locale symbol)
|G|&#10003;|Digit group separator (use locale symbol)
|MI||Explicit numeric sign place holder
|S||
|FM||Fill mode modifier; toggles between compact and fill modes for any elements following the modifier in the model.
|===
