////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= TRIM

Returns the string with leading and trailing characters removed.

== Syntax
----
TRIM(string[, characters])
----

== Usage

string:: The string expression to be trimmed

characters::  One or more characters to remove from the both side. If the parameter is omitted, the function will remove space characters.

See also xref:ltrim.adoc[LTRIM], xref:rtrim.adoc[RTRIM]